-- Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5
-- If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

-- 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

-- How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

import Data.List (nub)

pwrs :: Integer -> Integer -> Integer -> [Integer]
pwrs power start end = map ((^) power) [start..end]

ans' :: [Integer] -> Integer -> Integer -> [Integer]
ans' [] a b = []
ans' (x:xs) a b = pwrs x a b ++ ans' xs a b

ans :: Integer -> Integer -> Integer -> Integer -> Int
ans begin end start finish = length . nub $ ans' [begin..end] start finish
